---

- name: ensure /opt/cni exists
  file:
    path: "/opt/cni"
    state: "directory"

- name: copy cni binaries 
  copy:
    src: "{{ item }}"
    dest: "/opt/cni/{{ item | basename }}"
    mode: "0755"
  with_fileglob:
    - "{{ cni_release_cache_dir }}/bin/*"
