---

- name: install the kubelet and kube-proxy service files
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "kubelet.service"
    - "kube-proxy.service"
  notify: 
    - systemctl daemon-reload

- name: ensure k8s worker services are running
  service: 
    name: "{{ item }}"
    state: "running"
  with_items: "{{ k8s_worker_services }}"

