---

#
# Certificate Authority
#


# FIXME: maybe just delegate and do once?
# Get facts on all etcd nodes
- hosts:
    - all_instances 

# One node will host the CA
- hosts: tag_krole_etcd[0]
  roles:
    - certificate-authority
