---

- name: generate the CA certificate and private key
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: "{{ cfssl_dir }}" 
    creates: "ca.pem"

- name: verify CA certificate
  shell: openssl x509 -in ca.pem -text -noout
  args:
    chdir: "{{ cfssl_dir }}"
  changed_when: False

- name: install kubernetes-csr.json from template
  template:
    src: "kubernetes-csr.json"
    dest: "{{ cfssl_dir }}/kubernetes-csr.json"
  tags:
    - csr
 
- name: generate the Kubernetes certificate and private key
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes 
  args:
    chdir: "{{ cfssl_dir }}"
    creates: "kubernetes.pem"

- name: verify kubernetes.pem
  shell: openssl x509 -in kubernetes.pem -text -noout
  args:
    chdir: "{{ cfssl_dir }}"
  changed_when: False
