---

- name: ensure ubuntu user has a .kube directory
  file:
    path: "/home/ubuntu/.kube"
    state: "directory"
    owner: "ubuntu"
    group: "ubuntu"

- name: install ubuntu users kubectl config file from template
  template:
    src: "kubectl-config"
    dest: "/home/ubuntu/.kube/config"
    owner: "ubuntu"
    group: "ubuntu"
