---

- name: install k8s controller config files
  copy:
    src: "{{ item }}"
    dest: "/var/lib/kubernetes"
  with_items: "{{ k8s_controller_config_files }}"

# FIXME: move to vars
- name: install systemd service files
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}" 
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify: systemctl daemon-reload
 
- meta: flush_handlers
