---

- ec2_vpc_net_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_network_name }}"
  register: vpc_network_facts
  ignore_errors: True

- set_fact:
    vpc_network_id: "{{ vpc_network_facts.vpcs[0].id }}"
  when: vpc_network_facts.vpcs[0].id is defined
