---

- ec2_vpc_net_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_network_name }}"
  register: vpc_network_facts

- debug:
    var: vpc_network_facts
    verbosity: 2

#- fail:
#    msg: "The k8s VPC has probably not been created yet"
#  when: vpc_network_facts.vpcs[0].id is undefined

- set_fact:
    vpc_network_id: "{{ vpc_network_facts.vpcs[0].id }}"
  when: vpc_network_facts.vpcs[0].id is defined
