---

- name: create nat gateway on public subnet
  ec2_vpc_nat_gateway:
    subnet_id: "{{ vpc_public_subnet_id }}"
    region: "{{ aws_region }}"
    if_exist_do_not_create: True
    wait: yes 
    wait_timeout: 600 
  register: vpc_nat_gateway

- debug:
    var: vpc_nat_gateway
    verbosity: 2

