---

- name: set default gateway for private subnet to nat gateway
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_network_id }}"
    region: "{{ aws_region }}"
    subnets:
      - "{{ vpc_private_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc_nat_gateway.nat_gateway_id }}"
        instance_id: "{{ vpc_nat_gateway.nat_gateway_id }}"
    resource_tags: { "KubernetesCluster": "{{ k8s_cluster_name }}" }
  register: vpc_nat_private_route_table

- debug:
    var: vpc_nat_private_route_table
    verbosity: 2

